// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
)

type Covid struct {
	ID        uuid.UUID `json:"id"`
	Nama      string    `json:"nama"`
	Kota      string    `json:"kota"`
	Sembuh    int32     `json:"sembuh"`
	Dirawat   int32     `json:"dirawat"`
	Meninggal int32     `json:"meninggal"`
	Total     int32     `json:"total"`
}
