// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Covid struct {
	ID        int64  `json:"id"`
	Nama      string `json:"nama"`
	Kota      string `json:"kota"`
	Sembuh    int64  `json:"sembuh"`
	Dirawat   int64  `json:"dirawat"`
	Meninggal int64  `json:"meninggal"`
	Total     int64  `json:"total"`
}
